const random_names = [
        "Aria",
        "Sofia",
        "Luna",
        "Eva",
        "Mia",
        "Isabella",
        "Hana",
        "Zara",
        "Emi",
        "Lila",
        "Maya",
        "Nina",
        "Elena",
        "Yuki",
        "Amara",
        "Aisha",
        "Leila",
        "Anya",
        "Aaliyah",
        "Olivia",
        "Aurora",
        "Sophie",
        "Nadia",
        "Ayla",
        "Celia",
        "Ethan",
        "Liam",
        "Milo",
        "Leo",
        "Sebastian",
        "Kai",
        "Mateo",
        "Dylan",
        "Caleb",
        "Aiden",
        "Lucas",
        "Finn",
        "Oscar",
        "Ravi",
        "Hugo",
        "Ezra",
        "Ivan",
        "Arjun",
        "Zayn",
        "Noah",
        "Oliver",
        "Asher",
        "Elijah",
        "Rohan",
        "Kaden"
]

function return_random_name(){
    return random_names[Math.floor(Math.random()*random_names.length)]
}

export {return_random_name}